# Generated by Django 5.0.5 on 2024-05-18 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_likepost"),
        ("core", "0002_post"),
    ]

    operations = []
