# Generated by Django 5.0.5 on 2024-05-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_merge_0002_likepost_0002_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowersCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follower", models.CharField(max_length=100)),
                ("user", models.CharField(max_length=100)),
            ],
        ),
    ]
